### ISSUE TITLE
FOLK E RETARDS

### ISSUE THREAD

**Issue by Kofoten** [ineentho/textspel#1]
Vi har retards här som använder git editorn eller något som pushar fakking instant så man måste merga varje jävla push. Sen när man väl mergat så måste man merga IGEN. Vill bara säga WHAT THE FUCKING FUCK IN THE HELLS OF FUCK!!!

**Comment by ineentho** [comment]
exempel på ett så kallat retard https://github.com/ineentho/textspel/commit/3950d903f80382c02fd470f40b106c3bbf8d4325

**Comment by Kofoten** [comment]
Har lärt mig --rebase iaf

**Comment by MonsterPenguin** [comment]
FOLK *ÄR RETARDS
