### ISSUE TITLE
FIGHT.JS

### ISSUE THREAD

**Issue by Kofoten** [ineentho/textspel#11]
DET ÄR FEL.

**Comment by MonsterPenguin** [comment]
DET DRAR.

Man kan slå Nicke och Henrik i ansiktet när man ligger död på marken

**Comment by Kofotsmordarn** [comment]
@MonsterPenguin Det kallas last hit.

**Comment by Nicke535** [comment]
Man dör ej av att ha 0 HP, man dör av att TA SKADA som tar en under 0 HP. Verkar det som. Ska köra fler tester.

**Comment by MonsterPenguin** [comment]
Dodge chance existerar :)
