### ISSUE TITLE
Friendslist

### ISSUE THREAD

**Issue by ineentho** [ineentho/textspel#18]
Ser det här bra ut tycker du? @MonsterPenguin http://i.imgur.com/OxOERRz.png

**Comment by ineentho** [comment]
@MonsterPenguin jag har fixat det gröna plupparna nu, dags att göra ditt

**Comment by Kofoten** [comment]
@MonsterPenguin den e sne på liten skärm.

**Comment by MonsterPenguin** [comment]
@Kofotsmordarn NÄHÄ? Är den? Bra att du är observant åtminstone!

**Comment by Kofoten** [comment]
@MonsterPenguin Gör något åt det då.

**Comment by Kofoten** [comment]
@MonsterPenguin Du har haft 9 dagar på dig nu!! Det ser skit ut: http://i.imgur.com/wXLtnWb.png

**Comment by MonsterPenguin** [comment]
Men enradersfixar är svåra, det har Henrik redan bevisat

**Comment by ineentho** [comment]
Vad menar du med det? :(

**Comment by Kofoten** [comment]
@MonsterPenguin Är detta inte klart?? Ska man kanske stänga sin issue då??

**Comment by MonsterPenguin** [comment]
@Kofotsmordarn  Förstår du hur många saker jag måste klicka på då? Det är åtminstone 2

**Comment by Kofoten** [comment]
Jo jättejobbigt jämfört med vad Henrik och jag måste göra när ni fakkar ur

**Comment by Kofoten** [comment]
Vad e nu detta?? Ska det vara såhär?? http://i.imgur.com/8SsPBZ5.png

**Comment by MonsterPenguin** [comment]
Va?? Vad är problemet här @Kofotsmordarn?

**Comment by Kofoten** [comment]
Blind??

**Comment by MonsterPenguin** [comment]
Ser inget fel med friendslisten @Kofotsmordarn

**Comment by Kofoten** [comment]
Så den ska alltså täcka loggan om man har liten skärm?? @MonsterPenguin
