### ISSUE TITLE
Trasiga fights

### ISSUE THREAD

**Issue by ineentho** [ineentho/textspel#19]
@Kofotsmordarn @Nicke535 Servern tycker av någon aledning att den här fighten är klar:
http://retardarenan.henrik.ninja/game/fight/57f6d350c81e97296a46f254

Den säger bara "Fight 57f6d350c81e97296a46f254 stored successfully.", så någon måste tycka att den är klar av nåon anledning

**Comment by Kofoten** [comment]
@ineentho Det syns juh inget lite mer felsökning först kanske.

**Comment by Kofoten** [comment]
http://retardarenan.henrik.ninja/game/fight/57f758cb63841b10352e201c verkar funka

**Comment by ineentho** [comment]
@Kofotsmordarn flera fighter igår blev sådana, men lämnar felsökningen åt dig :)

**Comment by Kofoten** [comment]
@Ineentho @Nicke535 Skulle gissa på någon bugg i någon modifier.
