### ISSUE TITLE
Dots är trasiga som fan

### ISSUE THREAD

**Issue by ineentho** [ineentho/textspel#2]
Fan då @Kofotsmordarn !

**Comment by Kofoten** [comment]
Hitta felet då

**Comment by ineentho** [comment]
Första felet: Poison läggs alltid på av någon konstig anledning

**Comment by Kofoten** [comment]
Sitter I bilkö kan inte göra ngt

**Comment by ineentho** [comment]
Har du inte en laptop i bilen för sådana tillfällen?

**Comment by Kofoten** [comment]
I bagageluckan

**Comment by ineentho** [comment]
Vilken miss

**Comment by Kofoten** [comment]
....

**Comment by Kofoten** [comment]
Vill någon hjälpa med dotjävlarna??

**Comment by ineentho** [comment]
Det är väl ändå ditt problem, tänker inte ens peta på dem med en pinne

**Comment by ineentho** [comment]
http://i.imgur.com/QmtOQ4m.png

Dotsen försvinner ju aldrig :(

**Comment by ineentho** [comment]
Fuckin hell https://gyazo.com/1dbaa85aa3b60d33905bea7cead2987b

**Comment by ineentho** [comment]
Om jag inte tror på dig då?

**Comment by Kofoten** [comment]
Öppna igen då

**Comment by Kofoten** [comment]
henrik ts

**Comment by Nicke535** [comment]
Har nu gjort flertal tester, och kommit fram till att Bleed ej gör skada. Loggen säger att de gör det, men HPet säger något annat.

**Comment by Kofoten** [comment]
Efterbliv vi kom fram till det igår!!! :(
