### ISSUE TITLE
Servern verkar krascha när man accar friends

### ISSUE THREAD

**Issue by Kofoten** [ineentho/textspel#20]
@ineentho Servern blev inte glad när jag accade ny vän.

**Comment by ineentho** [comment]
Hur fan ska jag göra något åt det, lite mer felsökning först kanske :)

**Comment by Kofoten** [comment]
@Ineentho Lämmnas till dig

**Comment by MonsterPenguin** [comment]
@ineentho #PASSIVEAGGRESSIVESAVAGE2k16

**Comment by ineentho** [comment]
Rasmus förstår, copy-pastade halva hans meddelande

**Comment by ineentho** [comment]
I call BS
