### ISSUE TITLE
prefixes och items

### ISSUE THREAD

**Issue by Kofoten** [ineentho/textspel#22]
Ser ut som att folk noobat sig med prefixer och items: http://i.imgur.com/RTkAzhY.png
@Nicke535

**Comment by Nicke535** [comment]
Talar inte kod; vad, exact, betyder den där felloggen? Att feet prefixes Agile och spear prefixes Inexact är felskrivna?

Tar en titt lite snabbt...

**Comment by Nicke535** [comment]
Ok, de där prefixerna ska inte existera. Det du ser är antagligen resultatet av att ha en gammal item med dessa prefixer, som då måste genererats innan de togs bort. Detta problem kanske borde tas upp med henrik...

**Comment by Kofoten** [comment]
@ineentho Kan detta stämma??

**Comment by ineentho** [comment]
Så kan det nog vara, vad ska vi göra med de itemsen? Bara låta vara?

När vi har släppt spelet så lär vi se till att aldrig ta bort några prefixes

**Comment by Kofotsmordarn** [comment]
Känns diskuterat, stänger issue.

**Comment by Kofoten** [comment]
Känns som att detta är löst och vi har diskuterat. Stänger issue.
