### ISSUE TITLE
Multistrike

### ISSUE THREAD

**Issue by Kofoten** [ineentho/textspel#24]
Helt ärligt känns multistrike helt värdelöst. Den känns onödig och bara förvirrande för spelaren då hit chance och damage går att sätta i vapnet.

**Comment by Kofoten** [comment]
@Nicke535 Dessutom kommer du att försöka dela med 0 om vapnet inte har multistrike med den där koden.

**Comment by Nicke535** [comment]
Ska fixa "dela med 0" problemet. När det gäller multistrike anser jag att vi bör ha en diskussion om saken innan jag tar bort det. Just nu är det tänkt som en sorts "on-hit multiplier" för t.ex bleed. Men om ni andra inte tycker om det så har jag inget emot att ta bort det helt.

**Comment by Kofoten** [comment]
Du får gärna ha kvar det men då får du hitta på en annan mechanic för det. Kanske att man gör 75% av första slagets damage eller nåt

**Comment by Kofoten** [comment]
@Nicke535 Är detta fixat??

**Comment by Nicke535** [comment]
Multistrike orsakar nu helt enkelt fler slag med en viss procentchans varje slag. Detta gör det till den ENDA builden som kontras av dodge mer än av HP. Jag anser att detta issue är löst.
