### ISSUE TITLE
Sidan verkar helt död.

### ISSUE THREAD

**Issue by Nicke535** [ineentho/textspel#3]
Den länkar till något skumt quiz-program som inte existerar enligt google...

Oh, och jag märkte att vi har 666 commits, kan det ha med saken att göra?

**Comment by ineentho** [comment]
Kan lugna dig med att set inte var djävulen som var i farten, det var bara lite klassisk Henrik-retardhet. Råkade skriva över en configfil igår, men var för slö för att fixa, men det är fixat nu :)
