### ISSUE TITLE
Timestop!

### ISSUE THREAD

**Issue by ineentho** [ineentho/textspel#30]
@Kofotsmordarn

**Comment by Kofoten** [comment]
Ja det verkar juh inte vara något fel.

**Comment by MonsterPenguin** [comment]
Det var var väl det med om man har flera vapen och timestop?

**Comment by Kofoten** [comment]
Hörru noob klaga inte på sådant som e fixat.

**Comment by ineentho** [comment]
Fel på den här raden https://github.com/ineentho/textspel/blob/8f318ae55301748ffde1c54427ef14041623b576/server/fight.js#L90

Rätt säker på att det är om den som har timestop har fler vapen än fienden

**Comment by Kofoten** [comment]
Det där testade jag igår.

**Comment by Kofoten** [comment]
@ineentho @MonsterPenguin testade idag igen c490534
