### ISSUE TITLE
Jag slår mig själv i ansiktet, bl.a.

### ISSUE THREAD

**Issue by Nicke535** [ineentho/textspel#37]
Detta känns ju HELT fuckat:
http://imgur.com/a/dJmwl

**Comment by ineentho** [comment]
Hur fan är du röd en gång och grön en annan?

**Comment by Kofotsmordarn** [comment]
Du slåss mot dig själv. Inte så konstigt då...

**Comment by Kofoten** [comment]
@Nicke535 Det är olagligt att klona sig. http://i.imgur.com/MUARRQI.png
