### ISSUE TITLE
Npc:s stats verkar trasiga

### ISSUE THREAD

**Issue by Nicke535** [ineentho/textspel#43]
Dev Hands har mindre än 1 hit chance vid level 17, alla fiender har 1 damage lvl 17 osv. Något verkar strulat med matten.

**Comment by Kofoten** [comment]
Jag tror att någon missade att jag uppdaterade matten i en av mina senaste commits på grund av att ni ville att det skulle bli svårt upp mot level 90-100

**Comment by Nicke535** [comment]
Nej, jag menar, fiender gör ALLTID 1 SKADA. Så ska det inte vara...

**Comment by Nicke535** [comment]
Också, alla fiender verkar ha ca. 0.01 block multiplier av någon anledning.

**Comment by Kofoten** [comment]
10 / 80 är inte ett stort tal :)

**Comment by Kofoten** [comment]
tycket det fungerar korrekt

**Comment by Kofoten** [comment]
http://i.imgur.com/3xRyu2c.png
Ljug inte för mig körde på level 17
