### ISSUE TITLE
Temporary fight mesages

### ISSUE THREAD

**Issue by ineentho** [ineentho/textspel#5]
@MonsterPenguin @Nicke535 It's about time you do something about the temporary fight messages...

https://github.com/ineentho/textspel/blob/master/common/fight/text.js#L54

**Comment by Kofoten** [comment]
@MonsterPenguin @Nicke535  Fy inte ens ordentliga custom för ACB O.S.V

**Comment by Nicke535** [comment]
ACBn och SCBn har nu egna fight-messages, om än bara några stycken.

**Comment by Kofoten** [comment]
Messages funkar bra det e failade if-satser
