### ISSUE TITLE
Set prefixes existerar inte!!!!!!

### ISSUE THREAD

**Issue by Kofoten** [ineentho/textspel#7]
@MonsterPenguin @Nicke535  VI VILL HA PREFIXES PÅ SET!!!!!

**Comment by ineentho** [comment]
http://i.imgur.com/zQCTZTR.png

**Comment by ineentho** [comment]
Kanske skulle fixa eran skit?

**Comment by Nicke535** [comment]
Spear prefixes fixade; set prefixes måste justeras för varje set, eller ännu hällre för varje sorts SLOT i ett set. Behöver hjälp med formattering för detta.

**Comment by Kofoten** [comment]
Lul

**Comment by Kofoten** [comment]
Closing....
